image: php:7.1

before_script:
  - bash ci/docker_install.sh > /dev/null

test:unit:
  script:
    - phpunit --configuration phpunit.xml
test:coverage:
  script:
    - phpunit --configuration phpunit.xml --coverage-text --colors=never