name: typed-arrays
services:
  phpcli:
    type: php:8.1
    via: cli
    xdebug: true
    composer_version: 2-latest
    # Below only valid for via: cl
tooling:
  php:
    service: phpcli
  composer:
    service: phpcli
  phpcs:
    service: phpcli
    cmd: /app/vendor/bin/phpcs
  phpcbf:
    service: phpcli
    cmd: /app/vendor/bin/phpcbf
  rector:
    service: phpcli
    cmd: /app/vendor/bin/rector
  pest:
    service: phpcli
    cmd: /app/vendor/bin/pest
  phpstan:
    service: phpcli
    cmd: /app/vendor/bin/phpstan