<?php
/**
 * @author: StefanHelmer
 */

namespace Rockschtar\TypedArrays;

use Rockschtar\TypedArrays\Models\KeyValuePair;

class Hashmap extends TypedArray {
    public function current(): KeyValuePair {
        return parent::current(); // TODO: Change the autogenerated stub
    }

    protected function isDuplicate($value): bool {
        return false;
    }

    public function getType(): string {
        return KeyValuePair::class;
    }
}